# Generated by Django 2.0.3 on 2018-03-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='a', max_length=250, unique_for_date='pub_date'),
            preserve_default=False,
        ),
    ]
